### ISSUE TITLE
Inscrição

### ISSUE THREAD

**Issue by marcuslma** [Webschool-io/Curso-Kotlin#17]
Nome: Marcus Luís Maurmann Almeida
Email: marcuslma@gmail.com
Facebook: /marcus.maurmann
Twitter: @marcuslma
Telegram: @marcuslma

**Comment by andersonFaro9** [comment]
Por favor depositar o valor de R$ 25,00 reais na conta: Banco: Itaú, Nome: Anderson Faro Santana, Tipo de conta: Poupança, Agência: 1599, Conta: 15406 - 7, Cpf: 77950143568

**Comment by marcuslma** [comment]
Comprovante
![img_1054](https://user-images.githubusercontent.com/5174608/26858167-202b0d54-4b06-11e7-8c76-eb20f98aa0b4.PNG)

**Comment by andersonFaro9** [comment]
Opa...

Obrigado, cara...

O valor deve ser de 25

Agradeço o apoio...
